model: "DM3D"
#model: "pt_mamba"
trans_dim: 384
depth: 4
drop_path_rate: 0.3
rms_norm: False
use_cls_token: False
drop_path: 0.3
drop_out: 0.5
fetch_idx: [1, 2, 3]
k_group_size : 8
alpha: 100
beta : 1000
mamba_type: "v3"
num_group: 128
group_size: 32
fixed_dilations: [1,2,4]
base_dilation: 8
max_dilation: 16
levels: 2